{% set name = "ESMValTool" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf1bdb4e22dba58ef5a2ccda78e5d61afa8b9c9b9277aa1568ba81f7e4da5943

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools_scm
    - pip
  run:
    - cartopy >=0.18
    - cdo >=1.9.7
    - cdsapi >=0.5.1
    - cf-units >=2.1
    - cftime >=1.2.1
    - cmocean >=2.0
    - cython
    - dask >=2.12
    - eccodes !=2.19.0  # cdo dependency; something messed up with libeccodes.so
    - ecmwf-api-client  # in esmvalgroup channel
    - eofs >=1.4
    - esmpy >=8.0.1
    - esmvalcore >=2.3.1,<2.4  # in esmvalgroup channel
    - fiona >=1.8.18
    - gdal >=3.1.4
    - iris >=3.0.2,<3.0.4
    - jinja2 >=2.11
    - joblib >=1.0
    - lime
    # bug in 3.3.1, issue with nc-time-axis for >=3.4, can be lifted with move to iris>=3.0.4
    - matplotlib-base >3.3.1,<3.4
    - mpich<3.4  # avoid 3.4.1 external_2 from conda-forge like the plague; stable 3.3.2 OK
    - natsort >=7.1
    - nc-time-axis
    - netCDF4 >=1.5.6
    - numpy >=1.20
    - pandas >=1.2.3
    - pyproj >=2.1
    - python >=3.7
    - python-cdo >=1.5.4
    - pyyaml
    - rasterio  # replaces pynio
    - ruamel.yaml >=0.16.12
    - scikit-image
    - scikit-learn >=0.24
    - seaborn
    - seawater
    - shapely
    - xarray >=0.12.0
    - xesmf >=0.3
    - xgboost
    - xlsxwriter

test:
  commands:
    - esmvaltool --help
    - cmorize_obs --help
    - nclcodestyle --help
    - esmvaltool colortables --help
    - test_recipe --help
  imports:
    - esmvaltool

about:
  home: https://www.esmvaltool.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  description: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.

extra:
  recipe-maintainers:
    - zklaus
    - valeriupredoi
    - nielsdrost
    - jvegasbsc
    - bouweandela
